/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TrickOrTreatInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "DOORMAN()": FunctionFragment;
    "addVisitor((address,uint256))": FunctionFragment;
    "addVisitors(tuple[])": FunctionFragment;
    "bagContents((address,uint256))": FunctionFragment;
    "canRingDoorbell((address,uint256),(address,uint256))": FunctionFragment;
    "dailyVisits(uint256)": FunctionFragment;
    "getPlaceVisitHash((address,uint256),(address,uint256))": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getVisitorHash((address,uint256))": FunctionFragment;
    "getVisitorTodayHash((address,uint256))": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "hasVisitedBefore((address,uint256))": FunctionFragment;
    "initialize()": FunctionFragment;
    "listVisitors()": FunctionFragment;
    "placeVisits(uint256)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "ringDoorbell((address,uint256),(address,uint256))": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "treats(uint256)": FunctionFragment;
    "visitorHashes(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DOORMAN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addVisitor",
    values: [{ contractAddress: string; tokenId: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "addVisitors",
    values: [{ contractAddress: string; tokenId: BigNumberish }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bagContents",
    values: [{ contractAddress: string; tokenId: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "canRingDoorbell",
    values: [
      { contractAddress: string; tokenId: BigNumberish },
      { contractAddress: string; tokenId: BigNumberish }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyVisits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlaceVisitHash",
    values: [
      { contractAddress: string; tokenId: BigNumberish },
      { contractAddress: string; tokenId: BigNumberish }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVisitorHash",
    values: [{ contractAddress: string; tokenId: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "getVisitorTodayHash",
    values: [{ contractAddress: string; tokenId: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVisitedBefore",
    values: [{ contractAddress: string; tokenId: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listVisitors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "placeVisits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ringDoorbell",
    values: [
      { contractAddress: string; tokenId: BigNumberish },
      { contractAddress: string; tokenId: BigNumberish }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "visitorHashes",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DOORMAN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addVisitor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addVisitors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bagContents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canRingDoorbell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyVisits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlaceVisitHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVisitorHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVisitorTodayHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasVisitedBefore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listVisitors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placeVisits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ringDoorbell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "visitorHashes",
    data: BytesLike
  ): Result;

  events: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "Treated(address,uint256,uint16)": EventFragment;
    "Tricked(address,uint256,uint16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Treated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Tricked"): EventFragment;
}

export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string] & {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type TreatedEvent = TypedEvent<
  [string, BigNumber, number] & {
    visitorContractAddress: string;
    visitorTokenId: BigNumber;
    amount: number;
  }
>;

export type TrickedEvent = TypedEvent<
  [string, BigNumber, number] & {
    visitorContractAddress: string;
    visitorTokenId: BigNumber;
    amount: number;
  }
>;

export class TrickOrTreat extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TrickOrTreatInterface;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DOORMAN(overrides?: CallOverrides): Promise<[string]>;

    addVisitor(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addVisitors(
      _visitors: { contractAddress: string; tokenId: BigNumberish }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bagContents(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[number]>;

    canRingDoorbell(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[void]>;

    dailyVisits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getPlaceVisitHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getVisitorHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getVisitorTodayHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hasVisitedBefore(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    listVisitors(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    placeVisits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ringDoorbell(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    treats(arg0: BigNumberish, overrides?: CallOverrides): Promise<[number]>;

    visitorHashes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { contractAddress: string; tokenId: BigNumber }
    >;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  DOORMAN(overrides?: CallOverrides): Promise<string>;

  addVisitor(
    visitor: { contractAddress: string; tokenId: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addVisitors(
    _visitors: { contractAddress: string; tokenId: BigNumberish }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bagContents(
    visitor: { contractAddress: string; tokenId: BigNumberish },
    overrides?: CallOverrides
  ): Promise<number>;

  canRingDoorbell(
    visitor: { contractAddress: string; tokenId: BigNumberish },
    place: { contractAddress: string; tokenId: BigNumberish },
    overrides?: CallOverrides
  ): Promise<void>;

  dailyVisits(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

  getPlaceVisitHash(
    visitor: { contractAddress: string; tokenId: BigNumberish },
    place: { contractAddress: string; tokenId: BigNumberish },
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  getVisitorHash(
    visitor: { contractAddress: string; tokenId: BigNumberish },
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getVisitorTodayHash(
    visitor: { contractAddress: string; tokenId: BigNumberish },
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hasVisitedBefore(
    visitor: { contractAddress: string; tokenId: BigNumberish },
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  listVisitors(overrides?: CallOverrides): Promise<BigNumber[]>;

  placeVisits(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ringDoorbell(
    visitor: { contractAddress: string; tokenId: BigNumberish },
    place: { contractAddress: string; tokenId: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  treats(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

  visitorHashes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber] & { contractAddress: string; tokenId: BigNumber }
  >;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    DOORMAN(overrides?: CallOverrides): Promise<string>;

    addVisitor(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    addVisitors(
      _visitors: { contractAddress: string; tokenId: BigNumberish }[],
      overrides?: CallOverrides
    ): Promise<void>;

    bagContents(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<number>;

    canRingDoorbell(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    dailyVisits(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

    getPlaceVisitHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    getVisitorHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVisitorTodayHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hasVisitedBefore(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(overrides?: CallOverrides): Promise<void>;

    listVisitors(overrides?: CallOverrides): Promise<BigNumber[]>;

    placeVisits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ringDoorbell(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    treats(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

    visitorHashes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { contractAddress: string; tokenId: BigNumber }
    >;
  };

  filters: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "Treated(address,uint256,uint16)"(
      visitorContractAddress?: string | null,
      visitorTokenId?: BigNumberish | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      {
        visitorContractAddress: string;
        visitorTokenId: BigNumber;
        amount: number;
      }
    >;

    Treated(
      visitorContractAddress?: string | null,
      visitorTokenId?: BigNumberish | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      {
        visitorContractAddress: string;
        visitorTokenId: BigNumber;
        amount: number;
      }
    >;

    "Tricked(address,uint256,uint16)"(
      visitorContractAddress?: string | null,
      visitorTokenId?: BigNumberish | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      {
        visitorContractAddress: string;
        visitorTokenId: BigNumber;
        amount: number;
      }
    >;

    Tricked(
      visitorContractAddress?: string | null,
      visitorTokenId?: BigNumberish | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      {
        visitorContractAddress: string;
        visitorTokenId: BigNumber;
        amount: number;
      }
    >;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DOORMAN(overrides?: CallOverrides): Promise<BigNumber>;

    addVisitor(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addVisitors(
      _visitors: { contractAddress: string; tokenId: BigNumberish }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bagContents(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canRingDoorbell(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dailyVisits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPlaceVisitHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVisitorHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVisitorTodayHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasVisitedBefore(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    listVisitors(overrides?: CallOverrides): Promise<BigNumber>;

    placeVisits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ringDoorbell(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    treats(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    visitorHashes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DOORMAN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addVisitor(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addVisitors(
      _visitors: { contractAddress: string; tokenId: BigNumberish }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bagContents(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canRingDoorbell(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dailyVisits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPlaceVisitHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVisitorHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVisitorTodayHash(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasVisitedBefore(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    listVisitors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    placeVisits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ringDoorbell(
      visitor: { contractAddress: string; tokenId: BigNumberish },
      place: { contractAddress: string; tokenId: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    treats(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    visitorHashes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
